import { NBKRISTEvent } from '../types';

export const INITIAL_EVENTS: NBKRISTEvent[] = [
  {
    eventId: 'bmr-2026',
    title: 'International Conference on Biofilms & Microbiome Research (BMR 2026)',
    posterUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=1200&q=80',
    description: 'Join global researchers, microbiologists, and biomedical engineers for breakthrough presentations on biofilm dynamics, antimicrobial resistance, and microbiome engineering.',
    organization: 'Science & Humanities NBKRIST',
    organizationId: 'science-humanities',
    department: 'Science & Humanities',
    eventType: 'National Conference',
    date: '2026-10-25',
    endDate: '2026-10-28',
    featured: true,
    startTime: '09:00 AM',
    endTime: '05:00 PM',
    venue: 'International Convention Center, NBKRIST',
    registrationFee: '₹1,500 / Delegate',
    registrationDeadline: '2026-10-20',
    registrationMethod: 'googleForm',
    registrationUrl: 'https://forms.google.com',
    coordinatorName: 'Dr. Research Chair',
    coordinatorEmail: 'events@nbkrist.org',
    coordinatorPhone: '+91 9876543210',
    status: 'published',
    createdBy: 'institutional-admin',
    createdAt: new Date('2026-09-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    eventId: 'aaruush-2026',
    title: 'Aaruush 2026',
    posterUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    description: 'A National Level Techno-Management Fest rising in the spirit of innovation with competitive hackathons, managerial challenges, robotics leagues, and guest lectures.',
    organization: 'IEEE NBKRIST',
    organizationId: 'ieee-nbkrist',
    department: 'Interdisciplinary & Central Chapters',
    eventType: 'Technical Symposium',
    date: '2026-09-24',
    endDate: '2026-09-27',
    featured: true,
    startTime: '09:30 AM',
    endTime: '06:00 PM',
    venue: 'Central Auditorium & Main Grounds, NBKRIST',
    registrationFee: 'Free Entry',
    registrationDeadline: '2026-09-22',
    registrationMethod: 'googleForm',
    registrationUrl: 'https://forms.google.com',
    coordinatorName: 'IEEE Student Chair',
    coordinatorEmail: 'ieeenbkrist@nbkrist.org',
    coordinatorPhone: '+91 9876543211',
    status: 'registration_open',
    createdBy: 'institutional-admin',
    createdAt: new Date('2026-09-01').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    eventId: 'emeegt-2026',
    title: 'Two-Day National Workshop on Emerging Materials for Energy, Environment, and Green Technologies (EMEEGT 2026)',
    posterUrl: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=800&q=80',
    description: 'Hands-on experimental analysis and computational modeling of advanced photovoltaic materials, battery storage cells, and carbon-capture green technologies.',
    organization: 'MECH NBKRIST',
    organizationId: 'mech-nbkrist',
    department: 'Mechanical Engineering',
    eventType: 'Workshop & Hands-On',
    date: '2026-10-08',
    endDate: '2026-10-09',
    featured: false,
    startTime: '09:30 AM',
    endTime: '04:30 PM',
    venue: 'Renewable Energy Research Center, NBKRIST',
    registrationFee: '₹300',
    registrationDeadline: '2026-10-06',
    registrationMethod: 'googleForm',
    registrationUrl: 'https://forms.google.com',
    coordinatorName: 'Prof. Green Tech Lead',
    coordinatorEmail: 'mechnbkrist@nbkrist.org',
    coordinatorPhone: '+91 9876543212',
    status: 'registration_open',
    createdBy: 'institutional-admin',
    createdAt: new Date('2026-09-05').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    eventId: 'drone-building-2026',
    title: 'Build, Program & Fly: Embedded Applications & Hands-on Drone Building for School Students',
    posterUrl: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80',
    description: 'Interactive STEM workshop introducing secondary school students and young engineers to aerodynamics, flight controllers, Arduino coding, and live quadcopter piloting.',
    organization: 'ECE NBKRIST',
    organizationId: 'ece-nbkrist',
    department: 'Electronics & Communication Engineering',
    eventType: 'Workshop & Hands-On',
    date: '2026-10-08',
    endDate: '2026-10-09',
    featured: false,
    startTime: '10:00 AM',
    endTime: '04:00 PM',
    venue: 'Embedded Systems & Avionics Arena, NBKRIST',
    registrationFee: 'Free for School Delegates',
    registrationDeadline: '2026-10-06',
    registrationMethod: 'email',
    registrationEmail: 'ecenbkrist@nbkrist.org',
    coordinatorName: 'ECE Outreach Coordinator',
    coordinatorEmail: 'ecenbkrist@nbkrist.org',
    coordinatorPhone: '+91 9876543213',
    status: 'registration_open',
    createdBy: 'institutional-admin',
    createdAt: new Date('2026-09-05').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    eventId: 'asma-2026',
    title: '3rd International Conference on Asian Summer Monsoon Anticyclone (ASMA 2026)',
    posterUrl: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?auto=format&fit=crop&w=800&q=80',
    description: 'Global meteorological scientists and environmental engineers discuss tropospheric dynamics, aerosol transport, and climate resilience during the Asian Summer Monsoon.',
    organization: 'CIVIL NBKRIST',
    organizationId: 'civil-nbkrist',
    department: 'Civil Engineering',
    eventType: 'National Conference',
    date: '2026-10-08',
    endDate: '2026-10-09',
    featured: false,
    startTime: '09:00 AM',
    endTime: '05:00 PM',
    venue: 'Visvesvaraya Seminar Hall, NBKRIST',
    registrationFee: '₹500',
    registrationDeadline: '2026-10-05',
    registrationMethod: 'googleForm',
    registrationUrl: 'https://forms.google.com',
    coordinatorName: 'Civil Conference Chair',
    coordinatorEmail: 'civilnbkrist@nbkrist.org',
    coordinatorPhone: '+91 9876543214',
    status: 'published',
    createdBy: 'institutional-admin',
    createdAt: new Date('2026-09-05').toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    eventId: 'genai-unleashed-2026',
    title: 'GenAI Unleashed: A Two-Day Hands-on Workshop',
    posterUrl: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80',
    description: 'Dive into modern LLM fine-tuning, RAG architectures, multimodal AI agents, and production deployment using Python, LangChain, and modern APIs.',
    organization: 'CSE NBKRIST',
    organizationId: 'cse-nbkrist',
    department: 'Computer Science & Engineering',
    eventType: 'Workshop & Hands-On',
    date: '2026-10-08',
    endDate: '2026-10-09',
    featured: false,
    startTime: '09:30 AM',
    endTime: '04:30 PM',
    venue: 'Advanced AI & Cloud Computing Lab, NBKRIST',
    registrationFee: '₹200',
    registrationDeadline: '2026-10-06',
    registrationMethod: 'googleForm',
    registrationUrl: 'https://forms.google.com',
    coordinatorName: 'CSE AI Lead',
    coordinatorEmail: 'csenbkrist@nbkrist.org',
    coordinatorPhone: '+91 9876543215',
    status: 'registration_open',
    createdBy: 'institutional-admin',
    createdAt: new Date('2026-09-05').toISOString(),
    updatedAt: new Date().toISOString()
  }
];
